server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1

spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

endpoints:
  cors:
    allow-origins: http://localhost:8081
